### ISSUE TITLE
Private servers don't send client respawn zones

### ISSUE THREAD

**Issue by AlinaNova21** [screeps/backend-local#26]
The server doesn't send down respawnArea for the client, therefore respawn zones are invisible.
Both `map-stats` https://github.com/screeps/backend-local/blob/c9eeaa684b9de723bcd9b7e5e203be1a4a177b17/lib/game/api/game.js#L209
and `room-status` 
https://github.com/screeps/backend-local/blob/master/lib/game/api/game.js#L281

are missing the field, additionally, `place-spawn` doesn't seem to be checking novice or respawn status before allowing spawn. Which means unless I'm missing a check somewhere, its possible to spawn in a novice zone regardless of GCL.

**Comment by AlinaNova21** [comment]
Any update on this? This is a very annoying issue on Private Servers, the ScreepsPlus Seasonal server uses respawn areas for newly opened sectors, but with this bug, its hard to tell that it is a respawn zone.

**Comment by o4kapuk** [comment]
@ags131 Wait, PS does support novice areas but not respawn areas?
Will fix it at the upcoming update.

**Comment by AlinaNova21** [comment]
It supports the respawn areas driver/engine side, its just backend-local that doesn't support them correctly

**Comment by o4kapuk** [comment]
@ags131 thank you for the report and investigation, [this commit](https://github.com/screeps/backend-local/commit/8ba53e1a4e70943b46207af292a86a9e8e8e1b09) should fix the issue (will merge soon)
